INSERT INTO `university` (`university_id`, `university_name`) VALUES
(100, 'Abdullah Gül Üniversitesi'),
(101, 'Acıbadem Mehmet Ali Aydınlar Üniversitesi'),
(102, 'Adana Alparslan Türkeş Bilim Ve Teknoloji Üniversitesi'),
(103, 'Adıyaman Üniversitesi'),
(104, 'Afyon Kocatepe Üniversitesi'),
(105, 'Ağrı İbrahim Çeçen Üniversitesi'),
(106, 'Akdeniz Üniversitesi'),
(107, 'Aksaray Üniversitesi'),
(108, 'Alanya Alaaddin Keykubat Üniversitesi'),
(109, 'Alanya Hamdullah Emin Paşa Üniversitesi'),
(110, 'Altınbaş Üniversitesi'),
(111, 'Amasya Üniversitesi'),
(112, 'Anadolu Üniversitesi'),
(113,'Anka Teknoloji Üniversitesi'),
(114, 'Ankara Bilim Üniversitesi'),
(115, 'Ankara Hacı Bayram Veli Üniversitesi'),
(116, 'Ankara Medipol Üniversitesi'),
(117, 'Ankara Müzik ve Güzel Sanatlar Üniversitesi'),
(118, 'Ankara Sosyal Bilimler Üniversitesi'),
(119, 'Ankara Üniversitesi'),
(120, 'Ankara Yıldırım Beyazıt Üniversitesi'),
(121, 'Antalya Akev Üniversitesi'),
(122, 'Antalya Bilim Üniversitesi'),
(123, 'Ardahan Üniversitesi'),
(124, 'Artvin Çoruh Üniversitesi'),
(125, 'Ataşehir Adıgüzel Meslek Yüksekokulu'),
(126, 'Atatürk Üniversitesi'),
(127, 'Atılım Üniversitesi'),
(128, 'Avrasya Üniversitesi'),
(129, 'Avrupa Meslek Yüksekokulu'),
(130,'Aydın Adnan Menderes Üniversitesi'),
(131, 'Bahçeşehir Üniversitesi'),
(132, 'Balıkesir Üniversitesi'),
(133, 'Bandırma Onyedi Eylül Üniversitesi'),
(134, 'Bartın Üniversitesi'),
(135, 'Başkent Üniversitesi'),
(136, 'Batman Üniversitesi'),
(137, 'Bayburt Üniversitesi'),
(138, 'Beykent Üniversitesi'),
(139, 'Beykoz Üniversitesi'),
(140, 'Bezm-İ Âlem Vakıf Üniversitesi'),
(141, 'Bilecik Şeyh Edebali Üniversitesi'),
(142, 'Bingöl Üniversitesi'),
(143, 'Biruni Üniversitesi'),
(144, 'Bitlis Eren Üniversitesi'),
(145, 'Boğaziçi Üniversitesi'),
(146,'Bolu Abant İzzet Baysal Üniversitesi'),
(147,'Burdur Mehmet Akif Ersoy Üniversitesi'),
(148, 'Bursa Teknik Üniversitesi'),
(149, 'Bursa Uludağ Üniversitesi'),
(150, 'Bülent Ecevit Üniversitesi'),
(151, 'Çağ Üniversitesi'),
(152, 'Çanakkale Onsekiz Mart Üniversitesi'),
(153, 'Çankaya Üniversitesi'),
(154, 'Çankırı Karatekin Üniversitesi'),
(155, 'Çukurova Üniversitesi'),
(156, 'Demiroğlu Bilim Üniversitesi'),
(157, 'Dicle Üniversitesi'),
(158, 'Doğuş Üniversitesi'),
(159, 'Dokuz Eylül Üniversitesi'),
(160, 'Düzce Üniversitesi'),
(161, 'Ege Üniversitesi'),
(162, 'Erciyes Üniversitesi'),
(163, 'Erzincan Binali Yıldırım Üniversitesi'),
(164, 'Erzurum Teknik Üniversitesi'),
(165, 'Eskişehir Osmangazi Üniversitesi'),
(166, 'Eskişehir Teknik Üniversitesi'),
(167, 'Fatih Sultan Mehmet Vakıf Üniversitesi'),
(168, 'Fenerbahçe Üniversitesi'),
(169, 'Fırat Üniversitesi'),
(170, 'Galatasaray Üniversitesi'),
(171, 'Gazi Üniversitesi'),
(172, 'Gaziantep İslam Bilim ve Teknoloji Üniversitesi'),
(173, 'Gaziantep Üniversitesi'),
(174, 'Gebze Teknik Üniversitesi'),
(175, 'Giresun Üniversitesi'),
(176, 'Gümüşhane Üniversitesi'),
(177, 'Hacettepe Üniversitesi'),
(178, 'Hakkari Üniversitesi'),
(179, 'Haliç Üniversitesi'),
(180, 'Harran Üniversitesi'),
(181, 'Hasan Kalyoncu Üniversitesi'),
(182,'Hatay Mustafa Kemal Üniversitesi'),
(183, 'Hitit Üniversitesi'),
(184, 'Isparta Uygulamalı Bilimler Üniversitesi'),
(185, 'Iğdır Üniversitesi'),
(186, 'Işık Üniversitesi'),
(187, 'İbn Haldun Üniversitesi'),
(188, 'İhsan Doğramacı Bilkent Üniversitesi'),
(189, 'İnönü Üniversitesi'),
(190, 'İskenderun Teknik Üniversitesi'),
(191, 'İstanbul Arel Üniversitesi'),
(192, 'İstanbul Atlas Üniversitesi'),
(193, 'İstanbul Aydın Üniversitesi'),
(194, 'İstanbul Bilgi Üniversitesi'),
(195, 'İstanbul Esenyurt Üniversitesi'),
(196, 'İstanbul Galata Üniversitesi'),
(197, 'İstanbul Gedik Üniversitesi'),
(198, 'İstanbul Gelişim Üniversitesi'),
(199, 'İstanbul Kent Üniversitesi'),
(200, 'İstanbul Kültür Üniversitesi'),
(201, 'İstanbul Medeniyet Üniversitesi'),
(202, 'İstanbul Medipol Üniversitesi'),
(203, 'İstanbul Okan Üniversitesi'),
(204, 'İstanbul Rumeli Üniversitesi'),
(205, 'İstanbul Sabahattin Zaim Üniversitesi'),
(206, 'İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu'),
(207,'İstanbul Sağlık ve Teknoloji Üniversitesi'),
(208, 'İstanbul Şişli Meslek Yüksekokulu'),
(209, 'İstanbul Teknik Üniversitesi'),
(210, 'İstanbul Ticaret Üniversitesi'),
(211, 'İstanbul Topkapı Üniversitesi'),
(212, 'İstanbul Üniversitesi'),
(213, 'İstanbul Üniversitesi - Cerrahpaşa'),
(214, 'İstanbul Yeni Yüzyıl Üniversitesi'),
(215, 'İstanbul 29 Mayıs Üniversitesi'),
(216, 'İstinye Üniversitesi'),
(217, 'İzmir Bakırçay Üniversitesi'),
(218, 'İzmir Demokrasi Üniversitesi'),
(219, 'İzmir Ekonomi Üniversitesi'),
(220, 'İzmir Katip Çelebi Üniversitesi'),
(221, 'İzmir Kavram Meslek Yüksekokulu'),
(222, 'İzmir Tınaztepe Üniversitesi'),
(223, 'İzmir Yüksek Teknoloji Enstitüsü'),
(224, 'Kadir Has Üniversitesi'),
(225, 'Kafkas Üniversitesi'),
(226, 'Kahramanmaraş İstiklal Üniversitesi'),
(227, 'Kahramanmaraş Sütçü İmam Üniversitesi'),
(228, 'Kapadokya Üniversitesi'),
(229, 'Karabük Üniversitesi'),
(230, 'Karadeniz Teknik Üniversitesi'),
(231, 'Karamanoğlu Mehmetbey Üniversitesi'),
(232, 'Kastamonu Üniversitesi'),
(233, 'Kayseri Üniversitesi'),
(234, 'Kırıkkale Üniversitesi'),
(235, 'Kırklareli Üniversitesi'),
(236, 'Kırşehir Ahi Evran Üniversitesi'),
(237, 'Kilis 7 Aralık Üniversitesi'),
(238, 'Kocaeli Sağlık ve Teknoloji Üniversitesi'),
(239, 'Kocaeli Üniversitesi'),
(240, 'Koç Üniversitesi'),
(241, 'Konya Gıda Ve Tarım Üniversitesi'),
(242, 'Konya Teknik Üniversitesi'),
(243, 'Kto Karatay Üniversitesi'),
(244, 'Kütahya Dumlupınar Üniversitesi'),
(245, 'Kütahya Sağlık Bilimleri Üniversitesi'),
(246,'Lokman Hekim Üniversitesi'),
(247, 'Malatya Turgut Özal Üniversitesi'),
(248, 'Maltepe Üniversitesi'),
(249, 'Manisa Celâl Bayar Üniversitesi'),
(250, 'Mardin Artuklu Üniversitesi'),
(251, 'Marmara Üniversitesi'),
(252, 'Mef Üniversitesi'),
(253, 'Mersin Üniversitesi'),
(254, 'Mehmet Akif Ersoy Üniversitesi'),
(255, 'Melikşah Üniversitesi'),
(256, 'Mersin Üniversitesi'),
(257, 'Mimar Sinan Güzel Sanatlar Üniversitesi'),
(258, 'Mudanya Üniversitesi'),
(259, 'Muğla Sıtkı Koçman Üniversitesi'),
(260, 'Munzur Üniversitesi'),
(261, 'Muş Alparslan Üniversitesi'),
(262, 'Necmettin Erbakan Üniversitesi'),
(263, 'Nevşehir Hacı Bektaş Veli Üniversitesi'),
(264, 'Niğde Ömer Halisdemir Üniversitesi'),
(265, 'Nişantaşı Üniversitesi'),
(266, 'Nuh Naci Yazgan Üniversitesi'),
(267, 'Ondokuz Mayıs Üniversitesi'),
(268, 'Ordu Üniversitesi'),
(269, 'Orta Doğu Teknik Üniversitesi'),
(270, 'Osmaniye Korkut Ata Üniversitesi'),
(271, 'Ostim Teknik Üniversitesi'),
(272, 'Özyeğin Üniversitesi'),
(273, 'Pamukkale Üniversitesi'),
(274, 'Piri Reis Üniversitesi'),
(275, 'Recep Tayyip Erdoğan Üniversitesi'),
(276, 'Sabancı Üniversitesi'),
(277, 'Sağlık Bilimleri Üniversitesi'),
(278, 'Sakarya Uygulamalı Bilimler Üniversitesi'),
(279, 'Sakarya Üniversitesi'),
(280, 'Samsun Üniversitesi'),
(281, 'Sanko Üniversitesi'),
(282, 'Selçuk Üniversitesi'),
(283, 'Siirt Üniversitesi'),
(284, 'Sinop Üniversitesi'),
(285, 'Sivas Bilim ve Teknoloji Üniversitesi'),
(286, 'Sivas Cumhuriyet Üniversitesi'),
(287, 'Süleyman Demirel Üniversitesi'),
(288, 'Şırnak Üniversitesi'),
(289, 'Tarsus Üniversitesi'),
(290, 'Ted Üniversitesi'),
(291, 'Tekirdağ Namık Kemal Üniversitesi'),
(292, 'Tobb Ekonomi Ve Teknoloji Üniversitesi'),
(293, 'Tokat Gaziosmanpaşa Üniversitesi'),
(294, 'Toros Üniversitesi'),
(295, 'Trabzon Üniversitesi'),
(296, 'Trakya Üniversitesi'),
(297, 'Türk Hava Kurumu Üniversitesi'),
(298, 'Türk-Alman Üniversitesi'),
(299, 'Türkiye Uluslararası İslam, Bilim ve Teknoloji Üniversitesi'),
(300, 'Türk-Japon Bilim ve Teknoloji Üniversitesi'),
(301, 'Ufuk Üniversitesi'),
(302, 'Uşak Üniversitesi'),
(303, 'Üsküdar Üniversitesi'),
(304, 'Van Yüzüncü Yıl Üniversitesi'),
(305, 'Yalova Üniversitesi'),
(306, 'Yaşar Üniversitesi'),
(307, 'Yeditepe Üniversitesi'),
(308, 'Yıldız Teknik Üniversitesi'),
(309, 'Yozgat Bozok Üniversitesi'),
(310, 'Yüksek İhtisas Üniversitesi'),
(311, 'Zonguldak Bülent Ecevit Üniversitesi')